stages:
  - test
  - build


test:
  stage: test
  image: python:3.10
  script:
    - apt-get update && apt-get install -y espeak
    - python3.10 -m venv ENV
    - ENV/bin/python -m pip install -r requirements.txt
    - ENV/bin/python -m pip install -e .[dev]
    - ENV/bin/python -m spacy download en_core_web_md
    - cd src
    - ENV/bin/python -m pytest
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - public
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  tags:
    - docker


build:
  stage: build
  image: python:3.10
  script:
    - python3.10 -m venv ENV
    - ENV/bin/python -m pip install build
    - ENV/bin/python -m build .
  artifacts:
    paths:
      - dist
  tags:
    - docker
