conv_date = {'first': 1,
             'second':2,
             'third':3,
             'fourth':4,
             'fifth':5,
             'sixth':6,
             'seventh':7,
             'eight':8,
             'ninth':9,
             'tenth':10,
             'eleventh':11,
             'twelfth':12,
             'thirteenth':13,
             'fourteenth':14, 
             'fifteenth':15,
             'sixteenth':16,
             'seventeenth':17,
             'eighteenth':18,
             'nineteenth':19,
             'twentieth':20, 
             'twenty first':21, 
             'twenty second':22,
             'twenty third':23,
             'twenty fourth':24,
             'twenty fifth':25,
             'twenty sixth':26,
             'twenty seventh':27,
             'twenty eight':28,
             'twenty ninth':29,
             'thirty':30,
             'thirty first':31
            }
dates = ['first', 'second', 'third',
         'fourth', 'fifth', 'sixth', 'seventh',
          'eighth', 'ninth', 'tenth', 'eleventh', 'twelfth',
           'thirteenth', 'fourteenth', 'fifteenth',
            'sixteenth', 'seventeenth', 'eighteenth', 'nineteenth',
            'twentieth', 'twenty first', 'twenty second', 'twenty third', 'twenty fourth',
            'twenty fifth', 'twenty sixth','twenty seventh', 'twenty eight', 'twenty ninth', 'thirty',
             'thirty first']

months = {
          '01':"january",
          '02': "february",
          '03': "march",
          '04':"april",
          '05':"may",
          '06':"june",
          '07':"july",
          '08':"august",
          '09':"september",
          '10':"october",
          '11':"novemeber",
          '12':"december"
}

days_per_month = {
                  '01': '31',
                  '02': '28',
                  '03': '31',
                  '04': '30',
                  '05': '31',
                  '06': '30',
                  '07': '31',
                  '08': '31',
                  '09': '30',
                  '10': '31',
                  '11':'30',
                  '12': '31'
}
